blank_issues_enabled: false
contact_links:
  - name: 📞 Business Inquiries
    url: https://github.com/AdaptiveBS/Adaptive-Jewelry-Features
    about: For business inquiries, partnerships, or private feedback, please contact us through our main website
  - name: 🆘 Support
    url: https://github.com/AdaptiveBS/Adaptive-Jewelry-Features/discussions
    about: For general support questions, please use our Discussions section
  - name: 📚 Documentation
    url: https://github.com/AdaptiveBS/Adaptive-Jewelry-Features#readme
    about: Read our README for information about this repository and how to participate